"""MC/GDP 专用配置：只影响技术分析图，不参与基金收益估算。"""

MC_GDP_OVER_THRESHOLD = 0.765
MC_GDP_LOW_THRESHOLD = 0.60
MC_GDP_DEEP_LOW_THRESHOLD = 0.55

# 从上次成功获取起计时；失败另设退避，不伪造成功刷新时间。
MC_GDP_MARKET_CAP_TTL_HOURS = 48
MC_GDP_GDP_TTL_HOURS = 96
MC_GDP_FAILURE_RETRY_HOURS = 24
MC_GDP_REFRESH_BUDGET_SECONDS = 15
MC_GDP_CACHE_FILENAME = "a_share_mc_gdp.json"

MC_GDP_STATE_COLORS = {"OVER": "#E76F51", "LOW": "#2A9D8F",
                       "DEEP LOW": "#357C8C", "NEUTRAL": "#777777"}
MC_GDP_STATE_ALPHAS = {"OVER": .07, "LOW": .06, "DEEP LOW": .09}
MC_GDP_REGIME_LABEL_MIN_WIDTH_PX = 70
