"""限购变化图的独立样式；尺寸均为像素，不影响其他图片。"""

LIMIT_CHANGE_IMAGE_STYLE = {
    "width": 1080,
    "top_margin": 120,
    "bottom_margin": 60,
    "side_margin": 54,
    "padding": 32,
    "section_gap": 34,
    "row_height": 66,
    "title_font": 46,
    "section_font": 32,
    "body_font": 30,
    "small_font": 24,
    "value_font": 48,
    "background": "#F5F3EE",
    "card": "#FFFFFF",
    "text": "#18334B",
    "muted": "#687784",
    "accent": "#236B78",
    "accent_light": "#EAF3F1",
    "previous_bg": "#F0F2F4",
    "line": "#DFE5E8",
    "stripe": "#F6F8F9",
    "logo_opacity": 0.09,
    "logo_width_ratio": 0.48,
    "watermark_text": "鱼师AHNS",
    "export_dpi": 300,
}
