"""
夜盘海外基金观察配置。

夜盘观察复用盘前观察的基准、补偿仓位映射和展示项，只改变运行窗口、
缓存与输出产物。执行层只接受可校验到夜盘估值日的实时/扩展交易报价。
"""

from __future__ import annotations

from tools.configs.premarket_configs import (
    PREMARKET_BENCHMARK_SPECS,
    PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY,
    PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP,
)


NIGHT_START_HOUR_BJ = 10
NIGHT_START_MINUTE_BJ = 0
NIGHT_END_HOUR_BJ = 16
NIGHT_END_MINUTE_BJ = 0


NIGHT_BENCHMARK_SPECS = PREMARKET_BENCHMARK_SPECS
NIGHT_DEFAULT_RESIDUAL_BENCHMARK_KEY = PREMARKET_DEFAULT_RESIDUAL_BENCHMARK_KEY
NIGHT_FUND_RESIDUAL_BENCHMARK_MAP = PREMARKET_FUND_RESIDUAL_BENCHMARK_MAP


__all__ = [
    "NIGHT_BENCHMARK_SPECS",
    "NIGHT_DEFAULT_RESIDUAL_BENCHMARK_KEY",
    "NIGHT_END_HOUR_BJ",
    "NIGHT_END_MINUTE_BJ",
    "NIGHT_FUND_RESIDUAL_BENCHMARK_MAP",
    "NIGHT_START_HOUR_BJ",
    "NIGHT_START_MINUTE_BJ",
]
