"""
RSI 图表配置。

维护影响：
- 每一项配置对应一张 RSI 分析图及其输出路径。
- 新增或停用关注标的时，优先改这里；`stock_analysis.py` 只负责执行配置。
"""

RSI_ANALYSIS_CONFIGS = [
    {
        "name": "纳斯达克综合指数",
        "image": "output/nasdaq_analysis.png",
        "kwargs": {
            "symbol": ".IXIC",
            "display_name": "纳斯达克综合指数",
            "days": 220,
            "output_file": "output/nasdaq_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 80,
            "daily_rsi_low": 32,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 78,
            "weekly_rsi_low": 33,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 77,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            # 主程序默认只输出收盘价与成交量；想恢复本图底部 RSI 时改为 True。
            "show_rsi_panel": False,
            # 收盘价子图的 BOLL(20,2)；可按单个标的关闭或调整参数。
            "show_boll": True,
            "boll_window": 20,
            "boll_std_multiplier": 2.0,
            # 周 BOLL 在日线图以右连续阶梯线显示，和日线 BOLL 颜色区分。
            "show_weekly_boll": True,
            "weekly_boll_window": 20,
            "weekly_boll_std_multiplier": 2.0,
            # VIX 200 日均线减 20 日均线的极端状态带，仅显示红/深青极端日。
            "show_vix_state_band": True,
            "vix_state_negative_threshold": -5,
            "vix_state_positive_threshold": 5,
            # 跨市场节假日最多沿用最近 5 个自然日内的 VIX 风险状态。
            "vix_state_max_staleness_days": 5,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/nasdaq_rsi_signal_table.png",
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "红利低波华泰ETF",
        "image": "output/honglidibo_analysis.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "512890",
            "display_name": "红利低波华泰ETF",
            "days": 300,
            "output_file": "output/honglidibo_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 77,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 77,
            "weekly_rsi_low": 30,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 70,
            "monthly_rsi_low": 45,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            # 想恢复本图底部 RSI 时改为 True。
            "show_rsi_panel": False,
            "show_boll": True,
            "boll_window": 20,
            "boll_std_multiplier": 2.0,
            "show_weekly_boll": True,
            "weekly_boll_window": 20,
            "weekly_boll_std_multiplier": 2.0,
            # VIX 作为全球风险环境提示，所有指数和 ETF 图默认启用。
            "show_vix_state_band": True,
            "vix_state_negative_threshold": -5,
            "vix_state_positive_threshold": 5,
            "vix_state_max_staleness_days": 5,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/honglidibo_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "上证指数ETF：510210",
        "image": "output/shangzheng_analysis.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "510210",
            "display_name": "上证指数ETF：510210",
            "days": 300,
            "output_file": "output/shangzheng_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 78,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 78,
            "weekly_rsi_low": 30,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 75,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            # 想恢复本图底部 RSI 时改为 True。
            "show_rsi_panel": False,
            "show_boll": True,
            "boll_window": 20,
            "boll_std_multiplier": 2.0,
            "show_weekly_boll": True,
            "weekly_boll_window": 20,
            "weekly_boll_std_multiplier": 2.0,
            "show_vix_state_band": True,
            "vix_state_negative_threshold": -5,
            "vix_state_positive_threshold": 5,
            "vix_state_max_staleness_days": 5,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/shangzheng_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "德国DAX：159561",
        "image": "output/germany_dax.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "159561",
            "display_name": "德国DAX：159561",
            "days": 300,
            "output_file": "output/germany_dax.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 75,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 77,
            "weekly_rsi_low": 35,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 75,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            # 想恢复本图底部 RSI 时改为 True。
            "show_rsi_panel": False,
            "show_boll": True,
            "boll_window": 20,
            "boll_std_multiplier": 2.0,
            "show_weekly_boll": True,
            "weekly_boll_window": 20,
            "weekly_boll_std_multiplier": 2.0,
            "show_vix_state_band": True,
            "vix_state_negative_threshold": -5,
            "vix_state_positive_threshold": 5,
            "vix_state_max_staleness_days": 5,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/germany_dax_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "深证成指ETF：159943",
        "image": "output/shenzhen_component_analysis.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "159943",
            "display_name": "深证成指ETF：159943",
            "days": 300,
            "output_file": "output/shenzhen_component_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 78,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 78,
            "weekly_rsi_low": 30,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 75,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            # 想恢复本图底部 RSI 时改为 True。
            "show_rsi_panel": False,
            "show_boll": True,
            "boll_window": 20,
            "boll_std_multiplier": 2.0,
            "show_weekly_boll": True,
            "weekly_boll_window": 20,
            "weekly_boll_std_multiplier": 2.0,
            "show_vix_state_band": True,
            "vix_state_negative_threshold": -5,
            "vix_state_positive_threshold": 5,
            "vix_state_max_staleness_days": 5,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/shenzhen_component_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
    {
        "name": "中证2000ETF：560220",
        "image": "output/csi_2000_analysis.png",
        "use_realtime_param": True,
        "kwargs": {
            "symbol": "560220",
            "display_name": "中证2000ETF：560220",
            "days": 300,
            "output_file": "output/csi_2000_analysis.png",
            "daily_rsi_window": 9,
            "daily_rsi_high": 78,
            "daily_rsi_low": 30,
            "weekly_rsi_window": 9,
            "weekly_rsi_high": 78,
            "weekly_rsi_low": 30,
            "monthly_rsi_window": 9,
            "monthly_rsi_high": 75,
            "monthly_rsi_low": 40,
            "show_daily_signals": True,
            "show_weekly_signals": True,
            "show_monthly_signals": True,
            # 想恢复本图底部 RSI 时改为 True。
            "show_rsi_panel": False,
            "show_boll": True,
            "boll_window": 20,
            "boll_std_multiplier": 2.0,
            "show_weekly_boll": True,
            "weekly_boll_window": 20,
            "weekly_boll_std_multiplier": 2.0,
            "show_vix_state_band": True,
            "vix_state_negative_threshold": -5,
            "vix_state_positive_threshold": 5,
            "vix_state_max_staleness_days": 5,
            "print_signal_dates_flag": False,
            "save_signal_table": False,
            "signal_table_file": "output/csi_2000_table.png",
            "cache_dir": "cache",
            "retry": 3,
            "use_cache": True,
            "allow_eastmoney": False,
            "return_signals": True,
            "show_plot": False,
        },
    },
]


__all__ = ["RSI_ANALYSIS_CONFIGS"]
